// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Y6Bq3MPlGE_yKkx8t6KRoZ7pFCInZs0',
    appId: '1:39829495199:web:826b7faa07e427d1f871aa',
    messagingSenderId: '39829495199',
    projectId: 'flutter-map-5644b',
    authDomain: 'flutter-map-5644b.firebaseapp.com',
    storageBucket: 'flutter-map-5644b.firebasestorage.app',
    measurementId: 'G-R9DKSF74K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFGIZkZEytn5H7Ec1s2rI9rcnsSvH2d20',
    appId: '1:39829495199:android:b36b57f8e93aa9c0f871aa',
    messagingSenderId: '39829495199',
    projectId: 'flutter-map-5644b',
    storageBucket: 'flutter-map-5644b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXC2sexmoKw1EMzrYTMBZxjyp9KbRDmpY',
    appId: '1:39829495199:ios:23a4b38a451e09f0f871aa',
    messagingSenderId: '39829495199',
    projectId: 'flutter-map-5644b',
    storageBucket: 'flutter-map-5644b.firebasestorage.app',
    iosBundleId: 'com.example.dars13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXC2sexmoKw1EMzrYTMBZxjyp9KbRDmpY',
    appId: '1:39829495199:ios:23a4b38a451e09f0f871aa',
    messagingSenderId: '39829495199',
    projectId: 'flutter-map-5644b',
    storageBucket: 'flutter-map-5644b.firebasestorage.app',
    iosBundleId: 'com.example.dars13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Y6Bq3MPlGE_yKkx8t6KRoZ7pFCInZs0',
    appId: '1:39829495199:web:6b8118f1cb613e75f871aa',
    messagingSenderId: '39829495199',
    projectId: 'flutter-map-5644b',
    authDomain: 'flutter-map-5644b.firebaseapp.com',
    storageBucket: 'flutter-map-5644b.firebasestorage.app',
    measurementId: 'G-9P3R16Q913',
  );
}
